### ISSUE TITLE
Not working with latest Akka NuGets

### ISSUE THREAD

**Issue by PeterWimmerTmc** [akkadotnet/Akka.Logger.log4net#20]
The Akka.Logger.log4net NuGet is not compatible with recent Akka NuGets. I suspect it is due to changes in ILoggingAdapter, where methods have been moved to an extension class.

Please make a new NuGet available with updated Akka and log4net NuGets.

`[ERROR][07.25.2023 07:49:48.881Z][Thread 0025][akka://xxx/system/log1-Log4NetLogger] Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
Cause: System.MissingMethodException: Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
   at Akka.Logger.log4net.Log4NetLogger.<.ctor>b__2_8(InitializeLogger m)
   at lambda_method12(Closure, Object, Action`1, Action`1, Action`1, Action`1, Action`1)
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`6.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)`

**Comment by PeterWimmerTmc** [comment]
Is this repo still maintained?
